# Linux Box on WiFI AP: xxxx
# Linux Box IP: xxx.xx.xx.xxx
# Both MQTT Broker and ProtoPieConnect-Embedded are running on the same machine i.e. the Linux Box

# ProtoPieConnect configs
protopie_host: '192.168.0.209'
protopie_port: 9981
# MQTT configs
bridge_name: 'python_mqtt_bridge'
mqtt_broker_host: '192.168.0.209'
mqtt_broker_port: 1200

mqtt_secured: true # if set true, the preload.py will look for credentials in a .env file. 
# Remeber to set them accordingly then, in the .env file

# NOTE: MQTT Security credentials
# The mqtt user name and pwd are stored in a .env file and decoupled from here for security reasons
# Note: How to configure a MQTT broker with security credentials:
# 1. create a .env file (touch .env) in the same directory
# 2. enter the following data in that .env file. 
#    MQTT_USR='<username you used to configure your broker>'
#    MQTT_PWD='<password you used to configure your broker>'
# How to configure a mosquitto broker with username and password? 
#   Answer: https://gist.github.com/dattasaurabh82/c175aa913345cca64db55cb6983aebb9


# [TEST] The mapping of message flow, itself
mapping:
    # Mapping for when we have to translate socketio patterns to mqtt patterns, for different scenarios
    socketio_to_mqtt:
        msgid_to_topic: 
            - ['SWITCH', 'protopie/switch/state']
            - ['SWITCH', 'protopie/switch/state'] 
            - ['BRIGHTNESS', 'protopie/slider/value']           
        value_to_payload:
            - ['ON', 'on'] 
            - ['OFF', 'off']  
            - ['raw_value', 'raw_payload']                
    # Mapping for when we have to translate mqtt patterns to socketio patterns, for different scenarios
    mqtt_to_socketio:
        topic_to_msgid:
            - ['client/esp32_1_knob/button/state', 'ENCODER_BTN']
            - ['client/esp32_1_knob/button/state', 'ENCODER_BTN']          
            - ['client/esp32_1_knob/encoder/value', 'ENCODER_ANGLE']
            - ['client/esp32_1_knob/encoder/direction', 'DIRECTION']
        payload_to_value:
            - ['pressed', 'ON']             
            - ['released', 'OFF']
            - ['raw_payload', 'raw_value']
            - ['raw_payload', 'raw_value']